### ISSUE TITLE
crashes homebridge

### ISSUE THREAD

**Issue by wiz01-novice** [renssies/homebridge-slide-remote#2]
Very new to all this, but had this working nicely. Upgraded homebridge yesterday and now slide kills homebridge and it won't start up when slide-remote is installed :-(  Shame as I really like by Slide integration with the Home app.
I have attached what I think is the error from the log. I have removed and installed it a couple of times, and everything works OK until I install Slide-remote.

I note you may not update this often, but I hope my info helps you fix it when you can.

Many thanks
[Slide error.docx](https://github.com/renssies/homebridge-slide-remote/files/4630431/Slide.error.docx)

**Comment by renssies** [comment]
It looks like the slide-remote plugin is getting a time-out from the slide API when trying to get the slides on your account. You should check if `https://api.goslide.io/api` is reachable from the machine you run homebridge on. 

Homebridge crashes when this happens because of a mistake by me, I will fix this in a few minutes.

**Comment by renssies** [comment]
0.1.4 should include a fix for the crash. 

However, it might still be that no slides appear in your home app. In that case, make sure your account info in config.json is correct and that `https://api.goslide.io/api` is reachable.

**Comment by wiz01-novice** [comment]
Many thanks. I get this from the API link though.
![453B58AC-15CB-48BC-B489-029061955493](https://user-images.githubusercontent.com/65366309/82226495-d9cb2e80-9926-11ea-8a81-d4e381a34e59.png)

I’ll try updating the slide plug in this evening. Thanks for your quick reply.

**Comment by renssies** [comment]
Yeah, that page in safari should be correct and the API is reachable (even though it shows 404). 

If the API would not be reachable you would see a blank page with text in the middle with something like "The connection to the server timed out" or "The server is not reachable"

However, if you do continue to have issues, make sure you can reach the URL from the device that you also run Homebridge on. Sometimes different systems might have different network configurations, meaning some devices can and some devices can't access certain URLs

**Comment by wiz01-novice** [comment]
Excellent - working now :-)

I do get the  following error, but it runs ok. :-)

The plugin "homebridge-slide-remote" requires a Homebridge version of ^0.4.46 which does not satisfy the current Homebridge version of 1.1.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
[5/18/2020, 5:18:58 PM] The plugin "homebridge-slide-remote" requires Node version of ^10.0 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.
